name: sgrsoft
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.5.1+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cached_network_image: ^3.2.2
  dio: ^4.0.6
  dropdown_button2: ^1.8.8
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.11
  geolocator: ^9.0.2
  get_it: ^7.2.0
  google_maps_flutter: ^2.2.1
  google_polyline_algorithm: ^3.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.3
  http: ^0.13.5
  intl: ^0.17.0
  json_annotation: ^4.7.0
  latlng: ^0.2.0
  palette_generator: ^0.3.3+2
  google_maps_webservice:
    git:
      url: https://github.com/YakivGalkin/google_maps_webservice
  google_maps_flutter_web: ^0.4.0+3
  latlong2: ^0.8.1
  flutter_map: ^3.0.0
  geolocator_linux: ^0.1.2
  decorated_icon: ^1.2.1
  google_sign_in: ^5.4.2
  flutter_signin_button: ^2.0.0
  font_awesome_flutter: ^9.2.0
  flutter_polyline_points: ^1.0.0
  custom_info_window: ^1.0.1
  multiselect_formfield:
    git:
      url: https://github.com/hitshydev/multiselect_formfield
  material_floating_search_bar: ^0.3.7
  badges: ^2.0.3
  aligned_dialog: ^0.0.6
  autocomplete_textfield: ^2.0.1
  alice: ^0.2.5
  email_validator: ^2.1.17
  flutter_pw_validator: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^2.0.0
  build_runner: ^2.2.1
  json_serializable: ^6.4.1
  mockito: ^5.3.2

flutter_native_splash:
  color: "#8ac53f"
  image: assets/images/logo.png

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/fotos/
    - assets/images/iconos/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu/Ubuntu-Regular.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-Bold.ttf